refactor: restructure zfs zpool

diff --git a/cli/scripts/bootstrap b/cli/scripts/bootstrap
--- a/cli/scripts/bootstrap
+++ b/cli/scripts/bootstrap
@@ -151,30 +151,18 @@ if [ "$VERB" == "disks" ]; then
         # 7) create datasets
         run sudo zfs create rpool/nixos
         run sudo zfs create rpool/nixos/root -o mountpoint=legacy
-        run sudo zfs create rpool/nixos/home -o mountpoint=legacy
-        run sudo zfs create rpool/nixos/var -o mountpoint=legacy
-        run sudo zfs create rpool/nixos/etc -o mountpoint=legacy
-        run sudo zfs create rpool/nixos/srv -o mountpoint=legacy
         run sudo zfs create rpool/nixos/nix -o mountpoint=legacy
         run sudo zfs create rpool/nixos/persist -o mountpoint=legacy
 
         # 8) empty snapshots for impermanence
         run sudo zfs snapshot rpool/nixos/root@blank
-        run sudo zfs snapshot rpool/nixos/home@blank
-        run sudo zfs snapshot rpool/nixos/var@blank
-        run sudo zfs snapshot rpool/nixos/etc@blank
-        run sudo zfs snapshot rpool/nixos/srv@blank
 
     elif [ "$ARG1" == "mount" ]; then
 
         # 10) mount filesystems
         run sudo mkdir -p /mnt
         run sudo mount -t zfs rpool/nixos/root /mnt
-        run sudo mkdir -p /mnt/home /mnt/var /mnt/etc /mnt/srv /mnt/nix /mnt/persist
-        run sudo mount -t zfs rpool/nixos/home /mnt/home
-        run sudo mount -t zfs rpool/nixos/var /mnt/var
-        run sudo mount -t zfs rpool/nixos/etc /mnt/etc
-        run sudo mount -t zfs rpool/nixos/srv /mnt/srv
+        run sudo mkdir -p /mnt/nix /mnt/persist
         run sudo mount -t zfs rpool/nixos/nix /mnt/nix
         run sudo mount -t zfs rpool/nixos/persist /mnt/persist
 
@@ -1229,6 +1217,10 @@ elif [ "$VERB" == "lanzaboote" ]; then
       exit 1
     fi
 
+    if ! [ "$MOUNT" == "" ]; then
+        echo "Error: unexpected root mount $MOUNT"
+        exit 1
+    fi
 
     if [ "$ARG1" == "create" ]; then
         nix shell nixpkgs#sbctl --command sudo sbctl create-keys
@@ -1248,6 +1240,11 @@ elif [ "$VERB" == "impermanence" ]; then
     if ! [[ "${ROLE:-}" =~ ^(laptop|server|pi)$ ]]; then
       echo "Error: unexpected role $ROLE" >&2
       exit 1
+    fi
+
+    if ! [ "$MOUNT" == "" ]; then
+        echo "Error: unexpected root mount $MOUNT"
+        exit 1
     fi
 
     if [ -n "$(sudo ls -A -- "$PERSIST_DIR_ROOT" 2>/dev/null)" ]; then
