refactor: cleanup

diff --git a/cli/scripts/bootstrap b/cli/scripts/bootstrap
--- a/cli/scripts/bootstrap
+++ b/cli/scripts/bootstrap
@@ -968,8 +968,8 @@ elif [ "$VERB" == "lanzaboote" ]; then
 
 elif [ "$VERB" == "impermanence" ]; then
 
-    if [ -d "$PERSIST_DIR_ROOT" ]; then
-        echo "Error: $PERSIST_DIR_ROOT already exists" >&2
+    if [ -n "$(ls -A -- "$PERSIST_DIR_ROOT" 2>/dev/null)" ]; then
+        echo "Error: $PERSIST_DIR_ROOT is not empty" >&2
         exit 1
     fi
 
