fix: redirect script errors to stderr

diff --git a/scripts/edit b/scripts/edit
--- a/scripts/edit
+++ b/scripts/edit
@@ -11,7 +11,7 @@ if [ "$ROLE" == "laptop" ]; then
 elif [ "$ROLE" == "server" ]; then
     SOPS_DIR="/var/lib/sops-nix"
 else
-    echo "Error: unexpected role $NIXOS_ROLE"
+    echo "Error: unexpected role $NIXOS_ROLE" >&2
     exit 1
 fi
 SECRETS="$VARS_DIR/secrets.yaml"
@@ -21,6 +21,6 @@ if [ "$1" == "vars" ]; then
 elif [ "$1" == "sops" ]; then
     sudo GNUPGHOME="$SOPS_DIR" sops vars/secrets.yaml
 else
-    echo "Error: expected argument 'vars' or 'sops'"
+    echo "Error: expected argument 'vars' or 'sops'" >&2
     exit 1
 fi
diff --git a/scripts/nixos b/scripts/nixos
--- a/scripts/nixos
+++ b/scripts/nixos
@@ -13,7 +13,7 @@ if [ -z "$NIXOS_ROLE" ]; then
 fi
 
 if ! [[ "$NIXOS_ROLE" =~ ^(server|laptop)$ ]]; then
-  echo "Error: unexpected role $NIXOS_ROLE"
+  echo "Error: unexpected role $NIXOS_ROLE" >&2
   exit 1
 fi
 
@@ -59,5 +59,5 @@ fi
 end_time=$(date +%s)
 end_date=$(date "+%Y-%m-%d %H:%M:%S")
 duration=$((end_time - start_time))
-echo
-echo "[nixos] finshed in ${duration}s"
+echo >&2
+echo "[nixos] finshed in ${duration}s" >&2
